module.exports = {
	apps: [
		{
			name: "CampMaster",
			script: "./CampMaster/index.js",
			"ignore_watch": [
				"node_modules",
				"logs/*",
				"*.log",
				"logs/pm2.log",
				"data",
				"commands/inactive",
				"events/inactive",
				"events/beta",
				"hidden",
				"register.js",
				".github/*",
				".gitignore",
				".git/*",
				".vscode/*",
				".eslintrc.js",
				".eslintignore",
				"LICENSE",
				"README.md",
				"package-lock.json",
				"package.json",
				"pm2.json",
				"*replit*",
			],
			"watch": true,
			"restart_delay": 1000,
			"time": true,
			"increment_var": "build",
			"env": {
				"DISCORD_TOKEN": "MTAzOTI5MjE5MTQ0NjY4MzY0OA.Gth96a.VbHdm_heAmjxmZQsSZGSgOFhY1lshNBCvFj_-o",
				"clientId": "1039292191446683648",
				"env": "CampMaster",
				"build": 0
			}
		},
		{
			name: "SkillCamp",
			script: "./SkillCamp/index.js",
			"ignore_watch": [
				"node_modules",
				"logs/*",
				"*.log",
				"logs/pm2.log",
				"data",
				"commands/inactive",
				"events/inactive",
				"events/beta",
				"hidden",
				"register.js",
				".github/*",
				".gitignore",
				".git/*",
				".vscode/*",
				".eslintrc.js",
				".eslintignore",
				"LICENSE",
				"README.md",
				"package-lock.json",
				"package.json",
				"pm2.json",
				"*replit*",
			],
			"watch": true,
			"restart_delay": 1000,
			"time": true,
			"increment_var": "build",
			"env": {
				"DISCORD_TOKEN": "MTAzNTI3NzI0NzUzNzQ4Nzk3Mg.GW9eRv.VrY2YHe9lHvpfpjozjeD18xxKhSxVHgY2bwm9I",
				"clientId": "1035277247537487972",
				"env": "SkillCamp",
				"build": 0
			}
		},
		{
			name: "SkillCoin",
			script: "./SkillCoin/index.js",
			"ignore_watch": [
				"node_modules",
				"logs/*",
				"*.log",
				"logs/pm2.log",
				"data",
				"commands/inactive",
				"events/inactive",
				"events/beta",
				"hidden",
				"register.js",
				".github/*",
				".gitignore",
				".git/*",
				".vscode/*",
				".eslintrc.js",
				".eslintignore",
				"LICENSE",
				"README.md",
				"package-lock.json",
				"package.json",
				"pm2.json",
				"*replit*",
			],
			"watch": true,
			"restart_delay": 1000,
			"time": true,
			"increment_var": "build",
			"env": {
				"DISCORD_TOKEN": "MTA3NDcxNTYzNzA0MzE4Mzc3Nw.GJn0JK.NN233AUVwM4B_MSNRdVmauGYO8qE2miXILg9gs",
				"clientId": "1074715637043183777",
				"env": "SkillCoin",
				//"build": 0
			}
		}
	],
};
